### ISSUE TITLE
Support scopes with parameters

### ISSUE THREAD

**Issue by vRallev** [amzn/kotlin-inject-anvil#1]
The code currently assumes that scope annotations have no parameters, e.g.
```kotlin
@Scope
annotation class SingleInAppScope
```

Since this ticket https://github.com/evant/kotlin-inject/issues/377 has been resolved, kotlin-inject supports parameters for scope annotations. The Anvil extensions should support scopes such as:
```kotlin
@Scope
annotation class SingleIn(val scope: KClass<*>)
```

**Comment by ZacSweers** [comment]
In my testing, this is working now in the latest kotlin-inject + KSP1. It's broken in KSP2 for now due to https://github.com/google/ksp/issues/2091
