### ISSUE TITLE
Components declared in `iosMain` can not find the merged interface on Kotlin 2.x

### ISSUE THREAD

**Issue by chrisbanes** [amzn/kotlin-inject-anvil#20]
When I declare a component in `iosMain`, we can not access the resulting merged interface, as it will be generated in the `iosSimulatorArm64` gen folder (or `iosArm64`, etc), which then breaks compilation.

This is related to the recent `KmpComponentCreate` feature added in kotlin-inject 0.7.x, which works around the same source set isolation in K2. https://github.com/evant/kotlin-inject/blob/v0.7.0/docs/multiplatform.md. Added in https://github.com/evant/kotlin-inject/pull/370 by @eygraber.

Hiding the interface, as per #8, and making the inheritance automatic may well fix this.

One way around this would be to declare everything in `commonMain`, but that doesn't always work when we need to declare platform-specific inputs (and outputs) on the component.

## Repro:

`src/iosMain/kotlin/com/foo/bar`:

``` kotlin
@ApplicationScope
@MergeComponent
@Component
abstract class ApplicationObjectGraph : ApplicationObjectGraphMerged
```

This doesn't compile, as it can't find `ApplicationObjectGraphMerged`. `ApplicationObjectGraphMerged` is generated, but in `build/generated/ksp/iosSimulatorArm64/iosSimulatorArm64Main/kotlin/com/foo/bar` (for sim builds).

**Comment by chrisbanes** [comment]
Another way around this is to declare the component in every iOS target source set (`iosSimulatorArm64Main`,`iosArm64Main`, etc) as copies of each other. That's probably what I'll do for now to unblock.

**Comment by eygraber** [comment]
Just checking, are you saying that `KmpComponentCreate` is causing the issue, or you would do something similar to resolve the issue?

**Comment by chrisbanes** [comment]
Sorry, `KmpComponentCreate` solves a similar issue.

**Comment by vRallev** [comment]
For my understanding, does this happen with KSP1 or KSP2? Or does KSP make no difference?

**Comment by chrisbanes** [comment]
We're using KSP1 and compiling with K2. It's K2 where the change is iirc.

**Comment by eygraber** [comment]
It happens because of [Separation of common and platform sources during compilation](https://kotlinlang.org/docs/whatsnew20.html#separation-of-common-and-platform-sources-during-compilation) introduced with Kotlin 2.0.0
