### ISSUE TITLE
Contributed multibindings in the same round are not picked up by a merged component

### ISSUE THREAD

**Issue by ZacSweers** [amzn/kotlin-inject-anvil#22]
Repro: https://github.com/slackhq/circuit/pull/1635

`./gradlew :samples:kotlin-inject:kspKotlin`

The multibinding hints are correctly generated, but they are seemingly not picked up and included into `AppComponentMerged` for some reason, which is what has me thinking this is a round ordering/deferral issue.

![image](https://github.com/user-attachments/assets/ddb2d980-a0b7-47f1-bf33-74fb8e37214e)

**Comment by ZacSweers** [comment]
Talked offline, I was missing that custom annotations also need to have code gen run over them 👍

**Comment by marenovakovic** [comment]
I'm facing same issue.
What is the solution.
I don't understand what "custom annotations also need to have code gen run over them" really means.
Are custom annotations in question Circuit code gen annotations?

**Comment by vRallev** [comment]
Did you follow the exact steps highlighted here? https://github.com/amzn/kotlin-inject-anvil?tab=readme-ov-file#custom-symbol-processors

**Comment by marenovakovic** [comment]
This is so unstable.
Every time I open a project I get different error.
I was facing same issue as described by Zac and now it's:
```
Storage for .... is already registered
```
so I can't test it with `@ContributesTo(AppScope::class)`.
When I fix other issues I'll comment back if steps worked or not.

**Comment by ZacSweers** [comment]
Without a repro case no one can really help you

**Comment by marenovakovic** [comment]
Here is the reproduction repository
https://github.com/marenovakovic/circuit-kotlin-inject-anvil-code-gen-reproduction

**Comment by marenovakovic** [comment]
now reproduction repo works fine...

**Comment by rk779** [comment]
> For now adding `@ContributesTo(AppScope:`

Hi @marenovakovic, was this issue fixed `[ksp] kotlin.io.FileAlreadyExistsException` for you? I'm also randomly getting this issue.
