### ISSUE TITLE
Upgrade to Kotlin 2.0

### ISSUE THREAD

**Issue by vRallev** [amzn/kotlin-inject-anvil#3]
Upgrade the project to the latest Kotlin and KSP versions.

**Comment by matejdro** [comment]
Just a clarification, does that mean that the project can still be used on Kotlin 2.0+, just that its build version is not that high?

**Comment by vRallev** [comment]
I think that's the case, but I haven't tried it myself. Note that KSP2 will very likely not work due to the many bugs.

**Comment by vRallev** [comment]
This was solved in #51
