### ISSUE TITLE
Support `replaces` attribute in `@ContributesBinding` and `@ContributesTo`

### ISSUE THREAD

**Issue by eygraber** [amzn/kotlin-inject-anvil#79]
What is the suggested approach for having an application component for tests?

My initial thought was to use `MergeComponent.exclude`, and [kimchi's Contribute*.replaces](https://github.com/r0adkll/kimchi?tab=readme-ov-file#exclusions--replacements) looks interesting as well.

**Comment by vRallev** [comment]
We use `exclude` for now, but long term we should bring back `replaces` from the original Anvil: https://github.com/square/anvil/blob/main/annotations/src/main/java/com/squareup/anvil/annotations/ContributesTo.kt#L52
