### ISSUE TITLE
Provide ActivityScope

### ISSUE THREAD

**Issue by eygraber** [amzn/kotlin-inject-anvil#80]
Most of the project's that I've worked on have an app scope, and an activity scope. I don't know how popular that pattern is, but on the off-chance that it is, could the library provide that?

**Comment by vRallev** [comment]
An `AppScope` marker class is provided in the `runtime-optional` module, but `ActivityScope` will not be added. That's too Android specific and too specific to your use case.

**Comment by eygraber** [comment]
Makes sense. 

What if it were less Android specific, like `UIScope` or `SessionScope`, or something like that?

**Comment by vRallev** [comment]
Same argument, many applications only need an app scope.
