### ISSUE TITLE
Support few parents scopes for @ContributesSubcomponent.Factory

### ISSUE THREAD

**Issue by vvvladvvvolkovvvskiy** [amzn/kotlin-inject-anvil#93]
I want to reuse a component(feature) between several parent scopes. As I understand, I can't do this now. 
Is that possible?

**Comment by vRallev** [comment]
The way `@ContributesSubcomponent` works is that it requires a trigger to generate the code. That is the parent scope. You can have argument for the factory, e.g.
```kotlin
@ContributesSubcomponent.Factory(AppScope::class)
interface Factory {
    fun createComponent(string: String, int: Int): ChildComponent
}
```
There we could support more components. Would this solve your use case?

**Comment by vvvladvvvolkovvvskiy** [comment]
Sorry for the time spent, I realized I asked a dumb question.

I have several levels of hierarchy and wanted to have a factory method in two components at different levels (specifying multiple scopes). But yes, it can be generated in the parent and accessed in all the child components.
